fix(wrong-sorting): removed wrong sorting by sku
sphereio/sphere-stock-export pull request #12
Opened 2016-12-09 14:39 UTC by LEQADA

Fixes #11 
@PhilippSpo, @emmenko please review

2016-12-12 06:33 UTC, hisabimbola requested changes
Can you provide test for this? ;)

2016-12-12 10:35 UTC, LEQADA commented
@hisabimbola there was no tests for this before. This solution is a workaround and not a fix of the real problem.  
Do we really need to write tests for workaround? 
Maybe it is more reasonable to fix it in SDK and write tests directly there?

2016-12-12 11:55 UTC, hisabimbola commented
Either in the SDK or not, we try to make sure that all our code is tested especially when possible.

2016-12-12 19:23 UTC, butenkor commented
@hisabimbola Unit test which checks that query is not using any sorting is enough or you had something else in mind?

2017-01-16 08:11 UTC, Siilwyn commented
Any update? 🤔

2017-01-16 09:42 UTC, butenkor commented
@Siilwyn what update do you expect?

2017-01-16 11:03 UTC, Siilwyn commented
@butenkor a test? Reply from @hisabimbola or @LEQADA?
Or all of the above ^^

2017-01-16 11:38 UTC, hisabimbola commented
Yeah, @butenkor that would be enough

2017-01-18 10:46 UTC, Siilwyn commented on src/spec/fetchstock.spec.coffee
> +    @fetchStocks.client.inventoryEntries.sort = (path) ->
You're modifying the function here permanently this causes other tests to fail if run earlier. Please use a spy.

2017-01-18 10:46 UTC, Siilwyn requested changes

2017-01-18 10:46 UTC, Siilwyn commented on src/spec/fetchstock.spec.coffee
> +    @fetchStocks.client.inventoryEntries.sort = (path) ->
You're modifying the function here permanently this causes other tests to fail if run earlier. Please use a spy.

2017-01-18 13:33 UTC, Siilwyn approved these changes

2017-01-18 16:04 UTC, hisabimbola requested changes

2017-01-18 16:04 UTC, hisabimbola commented on src/coffee/fetchstocks.coffee
> +    # Do NOT use custom sorting due to https://github.com/sphereio/sphere-node-sdk/issues/194
I am not sure we want to add this comments to the code, should be added to the commit or the PR

2017-01-18 16:04 UTC, hisabimbola commented on src/spec/fetchstock.spec.coffee
> +  # Due to issue https://github.com/sphereio/sphere-node-sdk/issues/194 we ensure that custom sorting is never used
this also...

2017-01-18 16:04 UTC, hisabimbola commented on src/spec/fetchstock.spec.coffee
> +  it 'should sort by id only', (done) ->
💯

2017-01-18 16:07 UTC, LEQADA commented on src/coffee/fetchstocks.coffee
> +    # Do NOT use custom sorting due to https://github.com/sphereio/sphere-node-sdk/issues/194
Nobody will notice this warning in commits or PR text. It is there to prevent somebody adding this "feature" again.

2017-01-18 16:08 UTC, LEQADA commented on src/spec/fetchstock.spec.coffee
> +  # Due to issue https://github.com/sphereio/sphere-node-sdk/issues/194 we ensure that custom sorting is never used
This comment explains why exactly "should sort by id only"

2017-01-18 16:09 UTC, hisabimbola commented on src/coffee/fetchstocks.coffee
> +    # Do NOT use custom sorting due to https://github.com/sphereio/sphere-node-sdk/issues/194
That's the job of a **failing test** not ~comments~

2017-01-18 16:11 UTC, LEQADA commented on src/coffee/fetchstocks.coffee
> +    # Do NOT use custom sorting due to https://github.com/sphereio/sphere-node-sdk/issues/194
Without that comments nobody will understand the point except you, @Siilwyn and @butenkor

2017-01-18 16:17 UTC, Siilwyn commented on src/coffee/fetchstocks.coffee
> +    # Do NOT use custom sorting due to https://github.com/sphereio/sphere-node-sdk/issues/194
Think I agree with Abi here. If in the future somebody thinks it's a good idea to sort by SKU your test will fail. Then he/she will find out that way. Or am I missing something?

2017-01-20 13:32 UTC, hisabimbola commented
Build is failing @LEQADA 

Please check it out

2017-01-20 14:35 UTC, LEQADA commented
@hisabimbola  I don't know why coveralls fails =/
Did you see this error before?

```
[error] "2017-01-20T14:30:41.746Z"  'error from getOptions'
/home/travis/build/sphereio/sphere-stock-export/node_modules/coveralls/bin/coveralls.js:18
        throw err;
              ^
Error: Command failed: fatal: Not a valid object name 8ea7b289e95d1be073096a1237ffd8de6a4b42a5
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
Warning: Command failed: =============================================================================
Writing coverage object [/home/travis/build/sphereio/sphere-stock-export/coverage/coverage.json]
Writing coverage reports at [/home/travis/build/sphereio/sphere-stock-export/coverage]
=============================================================================
/home/travis/build/sphereio/sphere-stock-export/node_modules/coveralls/bin/coveralls.js:18
        throw err;
Error: Command failed: fatal: Not a valid object name 8ea7b289e95d1be073096a1237ffd8de6a4b42a5
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

2017-01-20 15:18 UTC, Siilwyn commented
@LEQADA looks like we're not alone on [this issue](https://github.com/nickmerwin/node-coveralls/issues/80).

I ran the tests and coverage locally: all passed, no change in coverage.
Let's merge this. :)

2017-01-21 09:06 UTC, hisabimbola commented
We can't merge a failing build, but what I will propose is that we update the node version

Can be done in another PR that is merged before this

Cc @Siilwyn @LEQADA

2017-01-24 11:21 UTC, Siilwyn commented
I updated the versions: https://github.com/sphereio/sphere-stock-export/pull/13

2017-01-25 12:35 UTC, Siilwyn commented
Please rebase against master.

2017-02-02 19:51 UTC, butenkor commented
@LEQADA please check ASAP

2017-02-06 09:26 UTC, hisabimbola approved these changes

2017-02-06 09:28 UTC, merged

2017-02-06 09:32 UTC, Siilwyn commented
Please delete the branch after merging to prevent old branches lying around.

2017-02-09 13:39 UTC, butenkor commented
@hisabimbola @Siilwyn can you please merge and release it?